//
//  MBSDSColor.Pallet.swift
//  McBarSilDesignSystem
//
//  Created by Roberta McDonald on 28/11/24.
//

extension MBSDSColor {

    struct Pallet: Decodable {

        let actionDisabledBase: String
        let actionDisabledBaseInverse: String
        let actionNeutralEnabled: String
        let actionNeutralEnabledInverse: String
        let actionNeutralFocus: String
        let actionNeutralFocusInverse: String
        let actionNeutralHover: String
        let actionNeutralHoverInverse: String
        let actionNeutralPressed: String
        let actionNeutralPressedInverse: String
        let actionNeutralSelected: String
        let actionNeutralSelectedInverse: String
        let actionPrimaryEnabled: String
        let actionPrimaryEnabledInverse: String
        let actionPrimaryFocus: String
        let actionPrimaryFocusInverse: String
        let actionPrimaryHover: String
        let actionPrimaryHoverInverse: String
        let actionPrimaryPressed: String
        let actionPrimaryPressedInverse: String
        let actionPrimarySelected: String
        let actionPrimarySelectedInverse: String
        let actionSecondaryEnabled: String
        let actionSecondaryEnabledInverse: String
        let actionSecondaryFocus: String
        let actionSecondaryFocusInverse: String
        let actionSecondaryHover: String
        let actionSecondaryHoverInverse: String
        let actionSecondaryPressed: String
        let actionSecondaryPressedInverse: String
        let actionSecondarySelected: String
        let actionSecondarySelectedInverse: String

        let backgroundBase: String
        let backgroundBaseInverse: String

        let neutralBase: String
        let neutralBaseInverse: String
        let neutralExtended00: String
        let neutralExtended10: String
        let neutralExtended20: String
        let neutralExtended30: String
        let neutralExtended40: String
        let neutralExtended50: String
        let neutralExtended60: String
        let neutralExtended70: String
        let neutralExtended80: String
        let neutralExtended90: String

        let onColorEmphasisDisabled: String
        let onColorEmphasisDisabledInverse: String
        let onColorEmphasisHigh: String
        let onColorEmphasisHighInverse: String
        let onColorEmphasisLow: String
        let onColorEmphasisLowInverse: String
        let onColorEmphasisMedium: String
        let onColorEmphasisMediumInverse: String
        let onColorIndicatorHighlightBase: String
        let onColorIndicatorHighlightBaseInverse: String
        let onColorIndicatorHighlightSurface: String
        let onColorIndicatorHighlightSurfaceInverse: String
        let onColorIndicatorNegativeBase: String
        let onColorIndicatorNegativeBaseInverse: String
        let onColorIndicatorNegativeSurface: String
        let onColorIndicatorNegativeSurfaceInverse: String
        let onColorIndicatorPositiveBase: String
        let onColorIndicatorPositiveBaseInverse: String
        let onColorIndicatorPositiveSurface: String
        let onColorIndicatorPositiveSurfaceInverse: String
        let onColorSurfaceDisabled: String
        let onColorSurfaceDisabledInverse: String
        let onColorSurfaceHigh: String
        let onColorSurfaceHighInverse: String
        let onColorSurfaceLow: String
        let onColorSurfaceLowInverse: String
        let onColorSurfaceMedium: String
        let onColorSurfaceMediumInverse: String

        let outlineBase: String
        let outlineBaseFocus: String
        let outlineBaseFocusInverse: String
        let outlineBaseInverse: String

        let primaryBase: String
        let primaryBaseInverse: String
        let primaryExtended00: String
        let primaryExtended10: String
        let primaryExtended20: String
        let primaryExtended30: String
        let primaryExtended40: String
        let primaryExtended50: String
        let primaryExtended60: String
        let primaryExtended70: String
        let primaryExtended80: String
        let primaryExtended90: String

        let secondaryBase: String
        let secondaryBaseInverse: String

        let statusErrorBase: String
        let statusErrorBaseInverse: String
        let statusErrorBaseSurface: String
        let statusErrorBaseSurfaceInverse: String
        let statusInformativeBase: String
        let statusInformativeBaseInverse: String
        let statusInformativeBaseSurface: String
        let statusInformativeBaseSurfaceInverse: String
        let statusSuccessBase: String
        let statusSuccessBaseInverse: String
        let statusSuccessBaseSurface: String
        let statusSuccessBaseSurfaceInverse: String
        let statusWarningBase: String
        let statusWarningBaseInverse: String
        let statusWarningBaseSurface: String
        let statusWarningBaseSurfaceInverse: String

        let specialFixedBlack: String
        let specialFixedWhite: String
        let specialShimmerBase1: String
        let specialShimmerBase2: String
        let specialShimmerBaseInverse1: String
        let specialShimmerBaseInverse2: String

        init() {
            self.actionDisabledBase = ""
            self.actionDisabledBaseInverse = ""
            self.actionNeutralEnabled = ""
            self.actionNeutralEnabledInverse = ""
            self.actionNeutralFocus = ""
            self.actionNeutralFocusInverse = ""
            self.actionNeutralHover = ""
            self.actionNeutralHoverInverse = ""
            self.actionNeutralPressed = ""
            self.actionNeutralPressedInverse = ""
            self.actionNeutralSelected = ""
            self.actionNeutralSelectedInverse = ""
            self.actionPrimaryEnabled = ""
            self.actionPrimaryEnabledInverse = ""
            self.actionPrimaryFocus = ""
            self.actionPrimaryFocusInverse = ""
            self.actionPrimaryHover = ""
            self.actionPrimaryHoverInverse = ""
            self.actionPrimaryPressed = ""
            self.actionPrimaryPressedInverse = ""
            self.actionPrimarySelected = ""
            self.actionPrimarySelectedInverse = ""
            self.actionSecondaryEnabled = ""
            self.actionSecondaryEnabledInverse = ""
            self.actionSecondaryFocus = ""
            self.actionSecondaryFocusInverse = ""
            self.actionSecondaryHover = ""
            self.actionSecondaryHoverInverse = ""
            self.actionSecondaryPressed = ""
            self.actionSecondaryPressedInverse = ""
            self.actionSecondarySelected = ""
            self.actionSecondarySelectedInverse = ""
            self.backgroundBase = ""
            self.backgroundBaseInverse = ""
            self.neutralBase = ""
            self.neutralBaseInverse = ""
            self.neutralExtended00 = ""
            self.neutralExtended10 = ""
            self.neutralExtended20 = ""
            self.neutralExtended30 = ""
            self.neutralExtended40 = ""
            self.neutralExtended50 = ""
            self.neutralExtended60 = ""
            self.neutralExtended70 = ""
            self.neutralExtended80 = ""
            self.neutralExtended90 = ""
            self.onColorEmphasisDisabled = ""
            self.onColorEmphasisDisabledInverse = ""
            self.onColorEmphasisHigh = ""
            self.onColorEmphasisHighInverse = ""
            self.onColorEmphasisLow = ""
            self.onColorEmphasisLowInverse = ""
            self.onColorEmphasisMedium = ""
            self.onColorEmphasisMediumInverse = ""
            self.onColorIndicatorHighlightBase = ""
            self.onColorIndicatorHighlightBaseInverse = ""
            self.onColorIndicatorHighlightSurface = ""
            self.onColorIndicatorHighlightSurfaceInverse = ""
            self.onColorIndicatorNegativeBase = ""
            self.onColorIndicatorNegativeBaseInverse = ""
            self.onColorIndicatorNegativeSurface = ""
            self.onColorIndicatorNegativeSurfaceInverse = ""
            self.onColorIndicatorPositiveBase = ""
            self.onColorIndicatorPositiveBaseInverse = ""
            self.onColorIndicatorPositiveSurface = ""
            self.onColorIndicatorPositiveSurfaceInverse = ""
            self.onColorSurfaceDisabled = ""
            self.onColorSurfaceDisabledInverse = ""
            self.onColorSurfaceHigh = ""
            self.onColorSurfaceHighInverse = ""
            self.onColorSurfaceLow = ""
            self.onColorSurfaceLowInverse = ""
            self.onColorSurfaceMedium = ""
            self.onColorSurfaceMediumInverse = ""
            self.outlineBase = ""
            self.outlineBaseFocus = ""
            self.outlineBaseFocusInverse = ""
            self.outlineBaseInverse = ""
            self.primaryBase = ""
            self.primaryBaseInverse = ""
            self.primaryExtended00 = ""
            self.primaryExtended10 = ""
            self.primaryExtended20 = ""
            self.primaryExtended30 = ""
            self.primaryExtended40 = ""
            self.primaryExtended50 = ""
            self.primaryExtended60 = ""
            self.primaryExtended70 = ""
            self.primaryExtended80 = ""
            self.primaryExtended90 = ""
            self.secondaryBase = ""
            self.secondaryBaseInverse = ""
            self.statusErrorBase = ""
            self.statusErrorBaseInverse = ""
            self.statusErrorBaseSurface = ""
            self.statusErrorBaseSurfaceInverse = ""
            self.statusInformativeBase = ""
            self.statusInformativeBaseInverse = ""
            self.statusInformativeBaseSurface = ""
            self.statusInformativeBaseSurfaceInverse = ""
            self.statusSuccessBase = ""
            self.statusSuccessBaseInverse = ""
            self.statusSuccessBaseSurface = ""
            self.statusSuccessBaseSurfaceInverse = ""
            self.statusWarningBase = ""
            self.statusWarningBaseInverse = ""
            self.statusWarningBaseSurface = ""
            self.statusWarningBaseSurfaceInverse = ""
            self.specialFixedBlack = ""
            self.specialFixedWhite = ""
            self.specialShimmerBase1 = ""
            self.specialShimmerBase2 = ""
            self.specialShimmerBaseInverse1 = ""
            self.specialShimmerBaseInverse2 = ""
        }
    }
}
